async function buscarDados(entrada) {
    if (entrada === 'erro') {
        throw new Error('Entrada invÃ¡lida!');
    }
    return 'Dados encontrados!';
}


(async () => {
    try {
        const dados = await buscarDados('erro');
        console.log(dados);
    } catch (error) {
        console.error(error.message);
    }
})();